-- MySQL Script generated by MySQL Workbench
-- Sat May 23 17:54:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idcpf` INT NOT NULL,
  `nomecompleto` VARCHAR(45) NOT NULL,
  `datanasc` varchar(45) NOT NULL,
  `endereco` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idcpf`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idEvento` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `data/hora` VARCHAR(45) NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `preco` VARCHAR(45) NOT NULL,
  `faixa etaria` VARCHAR(45) NOT NULL,
  `imagem` VARCHAR(90) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `Pessoa_idcpf` INT NOT NULL,
  PRIMARY KEY (`idEvento`),
  INDEX `fk_Evento_Pessoa_idx` (`Pessoa_idcpf` ASC) VISIBLE,
  CONSTRAINT `fk_Evento_Pessoa`
    FOREIGN KEY (`Pessoa_idcpf`)
    REFERENCES `mydb`.`Pessoa` (`idcpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingresso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingresso` (
  `idIngresso` INT NOT NULL,
  `data` VARCHAR(45) NOT NULL,
  `Evento_idEvento` INT NOT NULL,
  `Pessoa_idcpf` INT NOT NULL,
  `local` VARCHAR(45) NOT NULL,
  `QRCode` VARCHAR(90) NULL,
  PRIMARY KEY (`idIngresso`),
  INDEX `fk_Ingresso_Evento1_idx` (`Evento_idEvento` ASC) VISIBLE,
  INDEX `fk_Ingresso_Pessoa1_idx` (`Pessoa_idcpf` ASC) VISIBLE,
  CONSTRAINT `fk_Ingresso_Evento1`
    FOREIGN KEY (`Evento_idEvento`)
    REFERENCES `mydb`.`Evento` (`idEvento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ingresso_Pessoa1`
    FOREIGN KEY (`Pessoa_idcpf`)
    REFERENCES `mydb`.`Pessoa` (`idcpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imovel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imovel` (
  `idImovel` INT NOT NULL,
  `fotos` VARCHAR(90) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `capacidade` INT NOT NULL,
  `dono` VARCHAR(45) NOT NULL,
  `contato` VARCHAR(15) NOT NULL,
  `descricao` VARCHAR(300) NOT NULL,
  `avaliacao` SMALLINT(10) NULL,
  `Pessoa_idcpf` INT NOT NULL,
  PRIMARY KEY (`idImovel`),
  INDEX `fk_Imovel_Pessoa1_idx` (`Pessoa_idcpf` ASC) VISIBLE,
  CONSTRAINT `fk_Imovel_Pessoa1`
    FOREIGN KEY (`Pessoa_idcpf`)
    REFERENCES `mydb`.`Pessoa` (`idcpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Imovel_has_Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Imovel_has_Pessoa` (
  `Imovel_idImovel` INT NOT NULL,
  `Pessoa_idcpf` INT NOT NULL,
  PRIMARY KEY (`Imovel_idImovel`, `Pessoa_idcpf`),
  INDEX `fk_Imovel_has_Pessoa_Pessoa1_idx` (`Pessoa_idcpf` ASC) VISIBLE,
  INDEX `fk_Imovel_has_Pessoa_Imovel1_idx` (`Imovel_idImovel` ASC) VISIBLE,
  CONSTRAINT `fk_Imovel_has_Pessoa_Imovel1`
    FOREIGN KEY (`Imovel_idImovel`)
    REFERENCES `mydb`.`Imovel` (`idImovel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Imovel_has_Pessoa_Pessoa1`
    FOREIGN KEY (`Pessoa_idcpf`)
    REFERENCES `mydb`.`Pessoa` (`idcpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
INSERT INTO Pessoa (idcpf, nomecompleto, datanasc, endereco, email, senha, sexo) VALUE (123, "Joao Pedro", "20/12/1996", "Rua X" ,"joao_giaocometti@hotmail.com", "123","M");
